
  export  class stockInspectionPledge{
    primeNumber: String;
    businessSegment: String;
    region: String;
    branchCode: String;
    branchName: String;
    nameOfBorrower: String;
    rMCreditHub: String;
    limit: String;
    frequency: String;
    jointInspection:String;
    janConductedBy: String;
    janConductedByOutsource: String;
    janDate: Date;
    febConductedBy: String;
    febConductedByOutsource: String;
    febDate: Date;
    marchConductedBy: String;
    marchConductedByOutsource: String;
    marchDate: Date;
    aprilConductedBy: String;
    aprilConductedByOutsource: String;
    aprilDate: Date;
    mayConductedBy: String;
    mayConductedByOutsource: String;
    mayDate: Date;
    juneConductedBy: String;
    juneConductedByOutsource: String;
    juneDate: Date;
    julyConductedBy: String;
    julyConductedByOutsource: String;
    julyDate: Date;
    augustConductedBy: String;
    augustConductedByOutsource: String;
    augustDate: Date;
    septemberConductedBy: String;
    septemberConductedByOutsource: String;
    septemberDate: Date;
    octoberConductedBy: String;
    octoberConductedByOutsource: String;
    octoberDate: Date;
    novemberConductedBy: String;
    novemberConductedByOutsource: String;
    novemberDate: Date;
    decemberConductedBy: String;
    decemberConductedByOutsource: String;
    decemberDate: Date;
    dataStatus: String;
    createdBy : String;

createdOn: String;
 modifiedBy:  String;
 modifiedOn :  String;
 deletedBy: String;
 deletedOn:String;

    year :String;

    yearly : String;
    yearlyDate  :String;
    yearlyOutsource : String;
    st1quater :  String;
    st1quaterOutsource :  String;
    st1quaterDate :  String;
    nd2qauter:  String;
    nd2qauterOutsource:  String;
    nd2qauterDate:  String;
    rd3quater:  String;
    rd3quaterOutsource:  String;
    rd3quaterDate:  String;
    th4quater:String;
    th4quaterOutsource:String;
    th4quaterDate:String;
    stsemianually :String;
    stsemianuallyOutsource :String;
    stsemianuallyDate :String;
    ndsemianually:String;
    ndsemianuallyOutsource:String;
    ndsemianuallyDate:String;

}